// Embed the circuit's verification key as base64 so the package works in Node and browsers
// without filesystem access. Run by `yarn build`; src/vk.ts is generated and gitignored.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const vk = readFileSync(join(root, 'src', 'pvium_identity.vk'));
const out = `// GENERATED by scripts/embed-vk.mjs — do not edit.
/** UltraHonk verification key for circuit/src/main.nr (keccak / EVM transcript). */
export const VK_BASE64 = '${vk.toString('base64')}';
/** sha256 of the raw vk bytes, for sanity-checking against the deployed verifier's build. */
export const VK_SHA256 = '0x${createHash('sha256').update(vk).digest('hex')}';
`;
writeFileSync(join(root, 'src', 'vk.ts'), out);
console.log(`embedded vk (${vk.length} bytes)`);
