// Embed the circuit's verification key as base64 so the package works in Node and browsers
// without filesystem access. Run by `yarn build`; src/vk.ts is generated and gitignored.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const vk = readFileSync(join(root, 'src', 'pvium_identity.vk'));
const version = JSON.parse(readFileSync(join(root, 'src', 'circuit-version.json'), 'utf8'));
const vkSha = '0x' + createHash('sha256').update(vk).digest('hex');
if (vkSha !== version.vkSha256) {
  throw new Error(`src/pvium_identity.vk hashes to ${vkSha} but circuit-version.json says ${version.vkSha256}; run yarn sync`);
}
const out = `// GENERATED by scripts/embed-vk.mjs — do not edit.
/** UltraHonk verification key for circuit/src/main.nr (keccak / EVM transcript). */
export const VK_BASE64 = '${vk.toString('base64')}';
/** sha256 of the raw vk bytes, for sanity-checking against the deployed verifier's build. */
export const VK_SHA256 = '${vkSha}';
/** The circuit version this SDK release verifies. Attestations from other versions are rejected. */
export const CIRCUIT_VERSION = ${version.circuitVersion};
`;
writeFileSync(join(root, 'src', 'vk.ts'), out);
console.log(`embedded vk (${vk.length} bytes) for circuit version ${version.circuitVersion}`);
