// Embed the P2ID address-derivation constants (vault init code hash, factory addresses per chain)
// from src/p2id.json into src/p2idConstants.ts. Run by `yarn build`; the .ts is generated and
// gitignored. When the Hardhat artifact for P2IDVault is present (../../contracts compiled), the
// init code hash is recomputed from it and must match; pass --update to rewrite p2id.json instead.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { keccak_256 } from '@noble/hashes/sha3';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const jsonPath = join(root, 'src', 'p2id.json');
const cfg = JSON.parse(readFileSync(jsonPath, 'utf8'));

const artifact = join(root, '..', '..', 'contracts', 'artifacts', 'src', 'P2IDVault.sol', 'P2IDVault.json');
if (existsSync(artifact)) {
  const { bytecode } = JSON.parse(readFileSync(artifact, 'utf8'));
  const hex = bytecode.startsWith('0x') ? bytecode.slice(2) : bytecode;
  const bytes = Uint8Array.from(hex.match(/../g).map((b) => parseInt(b, 16)));
  const actual = '0x' + Buffer.from(keccak_256(bytes)).toString('hex');
  if (actual !== cfg.vaultInitCodeHash) {
    if (process.argv.includes('--update')) {
      cfg.vaultInitCodeHash = actual;
      writeFileSync(jsonPath, JSON.stringify(cfg, null, 2) + '\n');
      console.log(`updated src/p2id.json vaultInitCodeHash -> ${actual}`);
    } else {
      throw new Error(`P2IDVault artifact hashes to ${actual} but src/p2id.json says ${cfg.vaultInitCodeHash}; run node scripts/embed-p2id.mjs --update`);
    }
  }
}

const out = `// GENERATED by scripts/embed-p2id.mjs from src/p2id.json — do not edit.
/** keccak256 of the P2IDVault creation code; with a factory address it fixes every vault address. */
export const P2ID_VAULT_INIT_CODE_HASH = '${cfg.vaultInitCodeHash}' as const;
/** Deployed PviumP2IdVaultFactory per EIP-155 chain id. */
export const P2ID_FACTORIES: Readonly<Record<number, \`0x\${string}\`>> = ${JSON.stringify(cfg.factories, null, 2)};
`;
writeFileSync(join(root, 'src', 'p2idConstants.ts'), out);
console.log(`embedded P2ID constants (${Object.keys(cfg.factories).length} factories)`);
