// Embed the P2ID address schemes from src/p2id.json into src/p2idConstants.ts. Run by `yarn build`;
// the .ts is generated and gitignored. When the Hardhat artifact for P2IDVault is present
// (../../contracts compiled), the CURRENT scheme's init code hash is recomputed from it and must
// match. `--update` rewrites it, but only while that scheme is unreleased (no factory recorded):
// a released scheme is frozen, and a vault change then needs a new p2id.vault.vN entry.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { keccak_256 } from '@noble/hashes/sha3';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const jsonPath = join(root, 'src', 'p2id.json');
const cfg = JSON.parse(readFileSync(jsonPath, 'utf8'));
const current = cfg.schemes[cfg.current];
if (!current) throw new Error(`src/p2id.json: current scheme "${cfg.current}" is not defined`);
for (const [name, s] of Object.entries(cfg.schemes)) {
  if (!/^p2id\.vault\.v[1-9][0-9]*$/.test(name)) throw new Error(`bad scheme name "${name}" (expected p2id.vault.vN)`);
  if (!/^0x[0-9a-f]{64}$/.test(s.vaultInitCodeHash)) throw new Error(`${name}: bad vaultInitCodeHash`);
  for (const env of ['production', 'sandbox']) {
    const f = s.factories?.[env];
    if (f === undefined) throw new Error(`${name}: factories.${env} missing (use null until deployed)`);
    if (f !== null && !/^0x[0-9a-fA-F]{40}$/.test(f)) throw new Error(`${name}: bad factories.${env}`);
  }
}

const artifact = join(root, '..', '..', 'contracts', 'artifacts', 'src', 'P2IDVault.sol', 'P2IDVault.json');
if (existsSync(artifact)) {
  const { bytecode } = JSON.parse(readFileSync(artifact, 'utf8'));
  const hex = bytecode.startsWith('0x') ? bytecode.slice(2) : bytecode;
  const bytes = Uint8Array.from(hex.match(/../g).map((b) => parseInt(b, 16)));
  const actual = '0x' + Buffer.from(keccak_256(bytes)).toString('hex');
  if (actual !== current.vaultInitCodeHash) {
    const released = Object.entries(current.factories).filter(([, f]) => f !== null);
    if (released.length > 0) {
      throw new Error(
        `P2IDVault now hashes to ${actual}, but ${cfg.current} is released (${released.map(([e, f]) => `${e} factory ${f}`).join(', ')}) and frozen at ` +
          `${current.vaultInitCodeHash}. A vault change moves every address: add the next p2id.vault.vN scheme to src/p2id.json and make it current.`,
      );
    }
    if (!process.argv.includes('--update')) {
      throw new Error(`P2IDVault artifact hashes to ${actual} but ${cfg.current} says ${current.vaultInitCodeHash}; run node scripts/embed-p2id.mjs --update`);
    }
    current.vaultInitCodeHash = actual;
    writeFileSync(jsonPath, JSON.stringify(cfg, null, 2) + '\n');
    console.log(`updated ${cfg.current} vaultInitCodeHash -> ${actual}`);
  }
}

const schemes = Object.fromEntries(
  Object.entries(cfg.schemes).map(([name, s]) => [name, { identityDomain: s.identityDomain, vaultInitCodeHash: s.vaultInitCodeHash, factories: s.factories }]),
);
const out = `// GENERATED by scripts/embed-p2id.mjs from src/p2id.json — do not edit.
export interface P2IDScheme {
  /** Domain prefix of the identity hash this scheme salts vaults with, e.g. "p2id.identity.v1". */
  identityDomain: string;
  /** keccak256 of the P2IDVault creation code; with the factory address it fixes every vault address. */
  vaultInitCodeHash: \`0x\${string}\`;
  /**
   * The PviumP2IdVaultFactory per Pvium environment. Deployed through the deterministic deployment
   * proxy, so within an environment it has one address on every EVM chain. "production" is the
   * mainnet stack, "sandbox" the testnet stack (a different Privy app and key set). Null until
   * that environment's first deployment is recorded.
   */
  factories: { production: \`0x\${string}\` | null; sandbox: \`0x\${string}\` | null };
}
/** Every P2ID address scheme this release can derive, keyed by domain. Older schemes stay forever. */
export const P2ID_SCHEMES = ${JSON.stringify(schemes, null, 2)} as const satisfies Record<string, P2IDScheme>;
export type P2IDSchemeName = keyof typeof P2ID_SCHEMES;
/** The scheme new payments should use. */
export const P2ID_SCHEME = '${cfg.current}' as const satisfies P2IDSchemeName;
`;
writeFileSync(join(root, 'src', 'p2idConstants.ts'), out);
console.log(`embedded P2ID schemes: ${Object.keys(cfg.schemes).join(', ')} (current ${cfg.current}; production ${current.factories.production ?? 'not deployed'}, sandbox ${current.factories.sandbox ?? 'not deployed'})`);
