// Embed the P2ID address schemes from src/p2id.json into src/p2idConstants.ts. Run by `yarn build`;
// the .ts is generated and gitignored. When the Hardhat artifact for P2IDVault is present
// (../../contracts compiled), the CURRENT scheme's init code hash is recomputed from it and must
// match. `--update` rewrites it, but only while that scheme is unreleased (factory still null):
// a released scheme is frozen, and a vault change then needs a new p2id.vault.vN entry.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { keccak_256 } from '@noble/hashes/sha3';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const jsonPath = join(root, 'src', 'p2id.json');
const cfg = JSON.parse(readFileSync(jsonPath, 'utf8'));
const current = cfg.schemes[cfg.current];
if (!current) throw new Error(`src/p2id.json: current scheme "${cfg.current}" is not defined`);
for (const [name, s] of Object.entries(cfg.schemes)) {
  if (!/^p2id\.vault\.v[1-9][0-9]*$/.test(name)) throw new Error(`bad scheme name "${name}" (expected p2id.vault.vN)`);
  if (!/^0x[0-9a-f]{64}$/.test(s.vaultInitCodeHash)) throw new Error(`${name}: bad vaultInitCodeHash`);
  if (s.factory !== null && !/^0x[0-9a-fA-F]{40}$/.test(s.factory)) throw new Error(`${name}: bad factory`);
}

const artifact = join(root, '..', '..', 'contracts', 'artifacts', 'src', 'P2IDVault.sol', 'P2IDVault.json');
if (existsSync(artifact)) {
  const { bytecode } = JSON.parse(readFileSync(artifact, 'utf8'));
  const hex = bytecode.startsWith('0x') ? bytecode.slice(2) : bytecode;
  const bytes = Uint8Array.from(hex.match(/../g).map((b) => parseInt(b, 16)));
  const actual = '0x' + Buffer.from(keccak_256(bytes)).toString('hex');
  if (actual !== current.vaultInitCodeHash) {
    if (current.factory !== null) {
      throw new Error(
        `P2IDVault now hashes to ${actual}, but ${cfg.current} is released (factory ${current.factory}) and frozen at ` +
          `${current.vaultInitCodeHash}. A vault change moves every address: add the next p2id.vault.vN scheme to src/p2id.json and make it current.`,
      );
    }
    if (!process.argv.includes('--update')) {
      throw new Error(`P2IDVault artifact hashes to ${actual} but ${cfg.current} says ${current.vaultInitCodeHash}; run node scripts/embed-p2id.mjs --update`);
    }
    current.vaultInitCodeHash = actual;
    writeFileSync(jsonPath, JSON.stringify(cfg, null, 2) + '\n');
    console.log(`updated ${cfg.current} vaultInitCodeHash -> ${actual}`);
  }
}

const schemes = Object.fromEntries(
  Object.entries(cfg.schemes).map(([name, s]) => [name, { identityDomain: s.identityDomain, vaultInitCodeHash: s.vaultInitCodeHash, factory: s.factory }]),
);
const out = `// GENERATED by scripts/embed-p2id.mjs from src/p2id.json — do not edit.
export interface P2IDScheme {
  /** Domain prefix of the identity hash this scheme salts vaults with, e.g. "p2id.identity.v1". */
  identityDomain: string;
  /** keccak256 of the P2IDVault creation code; with the factory address it fixes every vault address. */
  vaultInitCodeHash: \`0x\${string}\`;
  /**
   * The PviumP2IdVaultFactory. Deployed through the deterministic deployment proxy, so it has this
   * same address on every EVM chain. Null until the scheme's first deployment is recorded.
   */
  factory: \`0x\${string}\` | null;
}
/** Every P2ID address scheme this release can derive, keyed by domain. Older schemes stay forever. */
export const P2ID_SCHEMES = ${JSON.stringify(schemes, null, 2)} as const satisfies Record<string, P2IDScheme>;
export type P2IDSchemeName = keyof typeof P2ID_SCHEMES;
/** The scheme new payments should use. */
export const P2ID_SCHEME = '${cfg.current}' as const satisfies P2IDSchemeName;
`;
writeFileSync(join(root, 'src', 'p2idConstants.ts'), out);
console.log(`embedded P2ID schemes: ${Object.keys(cfg.schemes).join(', ')} (current ${cfg.current}, factory ${current.factory ?? 'not deployed yet'})`);
